### ISSUE TITLE
关于 CI

### ISSUE THREAD

**Issue by c-z-chen** [docschina/Recoil#96]
每次 push 之后，都会看到 CI 在跑 (例如 227234f 的 [CI](https://github.com/docschina/Recoil/runs/2691909543))；并且也能成功，可是访问 https://recoil.docschina.org/ 并不会显示新增的改动，这是为什么？

**Comment by KimYangOfCat** [comment]
同问 @QC-L  Babel仓库也是如此

**Comment by QC-L** [comment]
因为仓库的构建存在缓存，问题不大，后面可以直接访问官网了
